---
functional:
    - Незарегистрированный пользователь может попробовать поиграть, подключившись к лёгкой игре с ботом
    - Пользователь должен иметь возможность зарегистрироваться на сайте
    - Пользователь может авторизоваться на сайте под своим аккаунтом на Codebattle, через Github или Discord
    - Пользователь может соревноваться в написании кода с другими игроками, ботами, друзьями по ссылке
    - Пользователь может отправить запрос на игру любому игроку
    - Пользователь может принять или отклонить запрос на игру от любого игрока
    - Пользователь может создать игру, выбрав уровень, тип игры, время игры и задание
    - Пользователь может выбрать подходящую для себя игру в лобби
    - Во время игры пользователь может выбрать необходимый ему язык программирования
    - Пользователь может создать турнир, выбрав тип турнира, время начала, задание, уровень, количество игроков и язык программирования
    - После завершения игры пользователь получает очки рейтинга, из которых формируется общий рейтинг пользьователя
    - Пользователь может отследить свой рейтинг и рейтинг других пользователей
    - Пользователь может отредактировать свой профиль в настройках
    - В лобби есть чат для авторизованных пользователей
    - Во время игры у пользователей открыт чат, где можно отправлять сообщения
    - Пользователь может отправлять сообщения другому игроку лично 
    - Во время игры задание можно открыть на двух языках - русском или английском
    - Пользователи могут быть в роли наблюдателя любой игры
    - Пользователи могут просмотреть историю всех проведённых игр
    - Во время игры, игрок может сдаться
    - Пользователь может просмотреть все задания
    - Пользователь может создать свое задание
non-functional:
    - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
    - Сайт должен быть безопасным и защищать данные пользователя
    - Сайт должен быть удобным на мобильном устройстве
    - Сайт должен быть протестирован на совместимость с последними версиями браузеров
    - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
    - Во время игры игроки видят написание кода друг у друга в режиме он-лайн
    - Каждый игрок может проверить своё решение неограниченное количество раз
    - Если игрок вылетел из игры, он в любой момент, пока игра не закончена, может переподключиться
    - Когда один из игроков находит верное решение, должно быть модальное окно с победителем игры
    - Проигравший игрок может продолжить написание своего кода, а может выйти
    - Во время игры игроки не могут копировать код друг друга
    - Во время игры игроки не могут копировать текст задания
